[package]
name = "code_of_conduct_conformulator"
version = "0.1.0"
authors = ["David Alber <alber.david@gmail.com>"]

[dependencies]
lazy_static = "1.0.0"
reqwest = "0.8.4"
serde = "1.0.53"
serde_derive = "1.0.53"
serde_json = "1.0.17"
